"de_DE": {
    "hello": "Hallo",
    "english": "Englisch",
    "arabic": "Arabisch",
    "welcome": "Willkommen",
    "welcomes_you": "Heißt dich willkommen",
    "Sorry_for_the_inconvenience_but_we_are_performing_some_maintenanceatthemomentWewillbebackonlineshortly":
        "Wir entschuldigen uns für die Unannehmlichkeiten, aber wir führen derzeit einige Wartungsarbeiten durch. Wir sind in Kürze wieder online!",
    "comment1": "MARK: Anmeldebildschirm",
    "This_operation_was_not_performed_due_to_demo_mode":
        "Diese Operation wurde aufgrund des Demomodus nicht durchgeführt",
    "Single_Restaurant": "Restaurantbenutzer",
    "APP_pacakgename": "com.vedis.user",
    "To": "Zu",
    "Login": "Anmelden",
    "Signin_to_your_account": "Melden Sie sich bei Ihrem Konto an",
    "Email": "E-Mail",
    "Password": "Passwort",
    "Forgot_Password": "Passwort vergessen?",
    "OR": "-----  ODER  -----",
    "Dont_have_an_account": "Sie haben noch kein Konto",
    "Signup": "Registrieren",
    "Skip_continue": "Überspringen & Weiter",
    "Please_enter_valid_email_address":
        "Bitte geben Sie eine gültige E-Mail-Adresse ein",
    "Please_enter_all_details": "Bitte geben Sie alle Details ein",
    "comment2": "MARK: Registrierungsbildschirm",
    "Create_an_account_so_you_can_order_your_favourite_product_faster":
        "Erstellen Sie ein Konto, damit Sie Ihr Lieblingsessen noch schneller bestellen können",
    "Full_name": "Vollständiger Name",
    "Mobile": "Handy",
    "Referral_code_Optional": "Empfehlungscode (Optional)",
    "I_accept_the_terms_conditions":
        "Ich akzeptiere die Geschäftsbedingungen",
    "Already_have_an_account": "Sie haben bereits ein Konto",
    "Please_enter_full_name":
        "Bitte geben Sie den vollständigen Namen ein",
    "Please_enter_phone_no": "Bitte geben Sie die Telefonnummer ein",
    "Please_select_terms_conditions":
        "Bitte akzeptieren Sie die Geschäftsbedingungen",
    "comment3": "MARK: Teams & Bedingungen Bildschirm",
    "TeamsConditions": "Teams und Bedingungen",
    "comment4": "MARK: Passwort vergessen Bildschirm",
    "Forgot_Password_": "Passwort vergessen",
    "Are_you_sure_to_continue_as_a_guest":
        "Möchten Sie als Gast fortfahren?",
    "Enter_your_registered_email_address_below_We_will_send_new_password_in_your_email":
        "Geben Sie unten Ihre registrierte E-Mail-Adresse ein. Wir senden ein neues Passwort an Ihre E-Mail-Adresse.",
    "Submit": "Einreichen",
    "comment5": "MARK: E-Mail-Verifizierung Bildschirm",
    "OTP_Verification": "OTP-Verifizierung",
    "Check_your_email_for_OTP_Enter_OTP_below_and_proceed_further":
        "Überprüfen Sie Ihre E-Mails auf OTP. Geben Sie den OTP unten ein und fahren Sie fort.",
    "Enter_OTP_here": "Geben Sie hier den OTP ein",
    "Verify_Proceed": "Überprüfen & Weiter",
    "Dont_receive_an_OTP": "Sie haben keinen OTP erhalten?",
    "Resend_OTP": "OTP erneut senden",
    "comment6": "MARK: Startbildschirm",
    "Restaurant_User": "Restaurantbenutzer",
    "Welcome": "Willkommen zu",
    "Search_Here": "Suche hier...",
    "Categories": "Kategorien",
    "Trending": "Trendig",
    "Todays_special": "Tagesangebot",
    "Recommended": "Empfohlen",
    "Testimonials": "Kundenbewertungen",
    "ADD": "HINZUFÜGEN",
    "The_item_has_multtiple_customizations_added_Go_to_cart__to_remove_item":
        "Das Produkt wurde mehrfach angepasst. Gehen Sie zum Warenkorb, um das Element zu entfernen",
    "GO_TO_CART": "ZUM WARENKORB GEHEN",
    "CANCEL": "ABBRECHEN",
    "comment7": "MARK: Produktdetailbildschirm",
    "additional_tax": "Zusätzliche Steuer",
    "Inclusive_of_all_taxes": "Inklusive aller Steuern",
    "Description": "Beschreibung",
    "Customizable": "Anpassbar",
    "Related_roducts": "Ähnliche Produkte",
    "Add_to_cart": "In den Warenkorb legen",
    "Viewcart": "Warenkorb anzeigen",
    "comment8": "MARK: Filterbildschirm",
    "Filter_Options": "Filteroptionen",
    "Veg": "Gemüse",
    "Nonveg": "Nicht-vegetarisch",
    "Both": "Beides",
    "comment9": "MARK: Suchbildschirm",
    "Search": "Suche",
    "No_data_found": "Keine Daten gefunden",
    "comment10": "Favoritenliste Bildschirm",
    "Favorite_list": "Favoritenliste",
    "comment11": "Warenkorb Bildschirm",
    "selected_Customizable": "Ausgewählte Anpassungsoptionen",
    "Mycart": "Mein Warenkorb",
    "Continue": "Weiter",
    "Select_Option": "Option auswählen",
    "DELIVERY": "LIEFERUNG",
    "Checkout": "Zur Kasse",
    "Takeaway": "Zum Mitnehmen",
    "Cancel": "Abbrechen",
    "Please_select_option": "Bitte Option auswählen",
    "Youve_reached_the_maximum_units_allowedfor_the_purchase_of_this_item":
        "Sie haben die maximale Anzahl an Einheiten für den Kauf dieses Artikels erreicht",
    "Restaurant_is_closed_Try_after_some_time":
        "Das Restaurant ist geschlossen. Versuchen Sie es später noch einmal",
    "comment12": "Bestellzusammenfassung Bildschirm",
    "Order_Summary": "Bestellzusammenfassung",
    "Product_Summary": "Produktzusammenfassung",
    "Qty": "Menge:",
    "Promocode": "Promocode",
    "Selectpromo": "Promocode auswählen",
    "haveapromocode": "Haben Sie einen Promocode?",
    "Apply": "Anwenden",
    "Remove": "Entfernen",
    "Bill_Details": "Rechnungsdetails",
    "SubTotal": "Zwischensumme",
    "Tax": "Steuer",
    "Delivery_Fee": "Liefergebühr",
    "Discount_Offer": "Rabattangebot",
    "Total_pay": "Gesamtzahlung",
    "Deliveryaddress": "Lieferadresse",
    "SELECT": "AUSWÄHLEN",
    "Set_your_delivery_address": "Geben Sie Ihre Lieferadresse ein",
    "Please_select_delivery_address": "Bitte Lieferadresse auswählen",
    "Special_instructions": "Besondere Anweisungen",
    "Customer_information": "Kundeninformationen",
    "Write_order_instructions": "Schreiben Sie Bestellanweisungen",
    "Process_to_pay": "Zur Zahlung gehen",
    "You_are_not_eligeble_for_this_offer":
        "Sie sind nicht für dieses Angebot berechtigt",
    "Order_amount_must_be_between": "Der Bestellbetrag muss zwischen",
    "comment13": "Bildschirm Zahlungsoptionen",
    "Payment_Option": "Zahlungsoption",
    "Place_Order": "Bestellung aufgeben",
    "Please_select_payment_option": "Bitte Zahlungsoption auswählen",
    "You_dont_have_sufficient_wallet_amonut_Please_select_another_payment_option":
        "Sie haben nicht genügend Geld auf Ihrem Konto. Bitte wählen Sie eine andere Zahlungsoption",
    "comment14": "Bestellbestätigungs Bildschirm",
    "Success": "Erfolg",
    "Your_order_has_been_placed_successfully_will_be_process_by_system":
        "Ihre Bestellung wurde erfolgreich aufgegeben und wird vom System bearbeitet.",
    "Check_Order_Details": "Bestelldetails überprüfen",
    "comment15": "Meine Bestellungen Bildschirm",
    "My_Orders": "Meine Bestellungen",
    "Processing": "In Bearbeitung",
    "Completed": "Abgeschlossen",
    "Cancelled": "Abgebrochen",
    "Cash": "Barzahlung",
    "Wallet": "Geldbörse",
    "RazorPay": "RazorPay",
    "Stripepay": "Stripe",
    "Flutterwave": "Flutterwave",
    "Paystack": "Paystack",
    "MercadoPago": "MercadoPago",
    "myFatoorah": "myFatoorah",
    "paypal": "PayPal",
    "ToyyibPay": "ToyyibPay",
    "Delivery": "Lieferung",
    "Take_away": "Zum Mitnehmen",
    "Paymenttype": "Zahlungsart: ",
    "Placed": "Platziert",
    "Preparing": "In Vorbereitung",
    "Ready": "Bereit",
    "On_the_way": "Unterwegs",
    "Waiting_for_pickup": "Warten auf Abholung",
    "conmment16": "Bestelldetails Bildschirm",
    "Order_Details": "Bestelldetails",
    "Cancel_Order": "Bestellung stornieren",
    "Driver_information": "Fahrerinformationen",
    "Are_you_sure_to_cancel_this_order_If_yes_then_order_amount_Online_payment_OR_Wallet_payment_will_be_transferred_to_your_wallet":
        "Möchten Sie diese Bestellung wirklich stornieren? Wenn ja, wird der Bestellbetrag (Online-Zahlung ODER Geldbörse) auf Ihr Konto überwiesen.",
    "comment17": "Mein Profil Bildschirm",
    "Myprofile": "Mein Profil",
    "Settings": "Einstellungen",
    "Change_Password": "Passwort ändern",
    "My_Addresses": "Meine Adressen",
    "My_Wallet": "Meine Geldbörse",
    "Refer_Earn": "Empfehlen & Verdienen",
    "Notification_Settings": "Benachrichtigungseinstellungen",
    "Change_Layout": "Layout ändern",
    "Help_Contact_Us": "Hilfe & Kontakt",
    "Privacy_Policy": "Datenschutzbestimmungen",
    "About_Us": "Über uns",
    "FAQs": "FAQs",
    "Gallery": "Galerie",
    "Book_A_Table": "Tisch reservieren",
    "Blogs": "Blogs",
    "Our_Team": "Unser Team",
    "Logout": "Ausloggen",
    "Select_application_layout": "Anwendungslayout auswählen",
    "LTR": "LTR",
    "RTL": "RTL",
    "Are_you_sure_to_logout_from_this_app":
        "Möchten Sie sich von dieser App abmelden?",
    "Are_you_sure_to_exit_from_this_app":
        "Möchten Sie diese App wirklich verlassen?",
    "commment18": "Profil bearbeiten Bildschirm",
    "Edit_Profile": "Profil bearbeiten",
    "Save": "Speichern",
    "Select_image": "Bild auswählen",
    "Photo_library": "Fotobibliothek",
    "Camera": "Kamera",
    "comment19": "Passwort ändern Bildschirm",
    "Old_password": "Altes Passwort",
    "New_password": "Neues Passwort",
    "Confirm_password": "Passwort bestätigen",
    "Reset": "Zurücksetzen",
    "New_password_Confirm_password_must_be_same":
        "Neues Passwort und bestätigtes Passwort müssen übereinstimmen",
    "comment20": "Meine Adressen Bildschirm",
    "Home": "Zuhause",
    "Office": "Büro",
    "Other": "Sonstiges",
    "Add_New_Address": "Neue Adresse hinzufügen",
    "Are_you_sure_to_delete_this_address":
        "Möchten Sie diese Adresse wirklich löschen?",
    "Yes": "Ja",
    "No": "Nein",
    "comment21": "Adresse hinzufügen Bildschirm",
    "Add_Address": "Adresse hinzufügen",
    "Edit_Address": "Adresse bearbeiten",
    "Selectdelloca": "LIEFERORT AUSWÄHLEN",
    "Change": "Ändern",
    "Confirmlocation": "Standort bestätigen",
    "comment22": "Adresse bestätigen Bildschirm",
    "Confirm_Address": "Adresse bestätigen",
    "A_detailed_address_will_help_our_delivery_parnter_reach_your_doorstep_easily":
        "Eine detaillierte Adresse erleichtert unserem Lieferpartner das Erreichen Ihrer Haustür",
    "Complete_address": "Vollständige Adresse",
    "House_flate_Floorno": "Haus / Wohnung / Etage Nr.",
    "Apartment_Road_Area_Optional":
        "Wohnung / Straße / Gebiet (optional)",
    "saveas": "Speichern als",
    "HOME": "Zuhause",
    "OFFICE": "Büro",
    "OTHER": "Sonstiges",
    "Saveaddressdetails": "Adressdetails speichern",
    "comment23": "Meine Geldbörse Bildschirm",
    "Wallet_Money": "Geldbörsengeld",
    "Fast_Easy_Payments": "Schnelle & einfache Zahlungen",
    "Secure_Payments": "Sichere Zahlungen",
    "No_Document_Upload_Required": "Kein Dokumentupload erforderlich",
    "Total_Balance": "Gesamtsaldo",
    "WALLET_MONEY_Can_only_be_used_for_your_orders":
        "GELDBEUTEL-GELD kann nur für Ihre Essensbestellungen verwendet werden",
    "ADD_MONEY": "+ GELD HINZUFÜGEN",
    "comment24": "Geld hinzufügen Bildschirm",
    "Add_Money": "Geld hinzufügen",
    "Enteramount": "BETRAG EINGEBEN",
    "Procaddmoney": "FORTFAHREN ZUM GELD HINZUFÜGEN",
    "Total_Balance_": "Gesamtsaldo :",
    "NOTES": "ANMERKUNGEN :",
    "Wallet_Money_cannot_be_transferred_to_your_bank_account":
        "-> Geldbörsengeld kann nicht auf Ihr Bankkonto überwiesen werden.",
    "You_can_use_Wallet_Money_only_on_orders":
        "-> Sie können Geldbörsengeld nur für Restaurantbestellungen verwenden",
    "Please_enter_amount": "Bitte geben Sie den Betrag ein",
    "comment25": "Transaktionsverlauf Bildschirm",
    "Transaction_History": "Transaktionsverlauf",
    "Wallet_Order": "Bestellung über Geldbörse",
    "Order_Cancel": "Bestellung storniert",
    "Order_Id": "Bestellnummer : ",
    "Wallet_Recharge": "Geldbörsenaufladung",
    "Referral_Amount": "Empfehlungsbonus",
    "comment26": "Testimonial hinzufügen Bildschirm",
    "Add_Testimonial": "Testimonial hinzufügen",
    "Enteryoureview": "Geben Sie Ihre Bewertung ein",
    "commnet27": "Empfehlen & Verdienen Bildschirm",
    "Share": "TEILEN",
    "refer_code1":
        "Teilen Sie diesen Code mit einem Freund, und Sie beide könnten für",
    "refer_code2":
        "Bonusbetrag im Rahmen unseres Empfehlungsprogramms berechtigt sein.",
    "bonus_amount_under_our_referral_program":
        "Bonusbetrag im Rahmen unseres Empfehlungsprogramms.",
    "Use_this_code": "Verwenden Sie diesen Code",
    "to_register_with": "um sich zu registrieren mit",
    "get_bonus_amount": "& erhalten Sie einen Bonusbetrag",
    "comment28": "Benachrichtigungseinstellungen Bildschirm",
    "Push_Notifications": "Push-Benachrichtigungen",
    "keepthisonnoti":
        "Behalten Sie dies eingeschaltet, um Benachrichtigungen vom System zu erhalten",
    "Emails": "E-Mails",
    "Keep_this_on_to_receive_emails_from_system":
        "Behalten Sie dies eingeschaltet, um E-Mails vom System zu erhalten",
    "comment29": "Hilfe & Kontakt Bildschirm",
    "Contact_Us": "Kontaktiere uns",
    "Inquiry_form": "Anfrageformular",
    "First_name": "Vorname",
    "Last_name": "Nachname",
    "Message": "Nachricht",
    "comment30": "Tisch reservieren Bildschirm",
    "No_of_guest": "Anzahl der Gäste",
    "Date": "Datum",
    "Time": "Zeit",
    "Reservation_Type": "Reservierungstyp",
    "Special_Request_Optional": "Spezialwunsch (optional)",
    "Your_booking_request_is_registered_successfully":
        "Ihre Buchungsanfrage wurde erfolgreich registriert",
    "comment31": "Blogs-Bildschirm",
    "Posted_by": "Veröffentlicht von :",
    "comment32": "Details Bildschirm",
    "Blogs_details": "Blogdetails",
    "commnet32": "Datumsauswahl Bildschirm",
    "Done": "Fertig",
    "comment33": "Karteninformationen Bildschirm",
    "Card_information": "Karteninformationen",
    "Card_number": "Kartennummer",
    "Card_holder_name": "Name des Karteninhabers",
    "MM": "MM",
    "YYYY": "JJJJ",
    "CVV": "CVV",
    "comment34": "Zusätzlich",
    "Gravityinfotech": "Gravity Infotech",
    "Infotechgravitygmail": "info@vedis.berlin",
    "Darkmode": "Dunkelmodus",
    "Name": "Name",
    "Phoneno": "Telefonnummer",
    "Myadresses": "Meine Adressen",
    "Compaddress": "Vollständige Adresse",
    "Houseflate": "Haus / Wohnung / Etage Nr.",
    "Apartmentroad": "Wohnung / Straße / Gebiet",
    "Instrefund": "Sofortige Rückerstattungen",
    "Devbygravityinfo": "Entwickelt von Vedis",
    "Zero": "00",
    "Payment": "Zahlung",
    "Contectus": "Kontaktiere uns",
    "No91_70164": "+91 7016428845",
    "Company_address": "Green Road, Uttran, Surat, Gujarat, Indien",
    "Ordersummary": "Bestellübersicht",
    "Productsummary": "Produktübersicht",
    "Select": "AUSWÄHLEN",
    "Onlyforyou": "NUR FÜR DICH",
    "Ratingreview": "Bewertungen & Rezensionen",
    "Faqs": "FAQs",
    "Reservationtype": "Reservierungstyp",
    "Specialrequest": "Spezialwunsch (optional)",
    "ok": "Ok",
    "Continue_Shopping": "Weiter einkaufen"
  },